name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x
          - 14.x
          - 15.x
    steps:
      - uses: borales/actions-yarn@2.0.0
        with:
          cmd: install # yarn install
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn workspace channel-ts ci
      - run: yarn workspace channel-ts codecov
