name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2
      - name: INSTALL PROJECT DEPENDENCIES (yarn)
        run: yarn install
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test @tschannel/core
        run: yarn workspace @tschannel/core ci
      - name: Test @tschannel/transformer
        run: yarn workspace @tschannel/transformer test
  codecov-coverage-reporter:
    runs-on: ubuntu-latest
    name: codecov-coverage-reporter
    steps:
      - name: Collecting coverage data of @tschannel/core
        run: yarn workspace @tschannel/core codecov
      - name: Collecting coverage data pf @tschannel/transformer
        run: yarn workspace @tschannel/transformer codecov
    needs: ["build"]
  codacy-coverage-reporter:
      runs-on: ubuntu-latest
      name: codacy-coverage-reporter
      steps:
        - uses: actions/checkout@v2
        - name: list all directories
          run: ls
        - name: Upload coverage reports to codacy
          uses: codacy/codacy-coverage-reporter-action@master
          with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            coverage-reports: packages/tschannel/coverage/cobertura-coverage.xml,packages/tschannel-transformer/coverage/cobertura-coverage.xml
      needs: ["build"]
