name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2
      - name: INSTALL PROJECT DEPENDENCIES (yarn)
        run: yarn install
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test @tschannel/core
        run: yarn workspace @tschannel/core ci
      - name: Collecting coverage data of @tschannel/core
        run: yarn workspace @tschannel/core codecov
      - name: Test @tschannel/transformer
        run: yarn workspace @tschannel/transformer test
      - name: Collecting cpverage data pf @tschannel/transformer
        run: yarn workspace @tschannel/transformer codecov
