name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: INSTALL PROJECT DEPENDENCIES (yarn)
        run: yarn install
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test @vgerbot/channel
        run: yarn workspace @vgerbot/channel test
      - name: Build @vgerbot/channel
        run: yarn workspace @vgerbot/channel build
      - name: Upload coverage data of @vgerbot/channel to codecov
        run: yarn workspace @vgerbot/channel codecov
      - name: Upload coverage reports to codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: packages/core/coverage/cobertura-coverage.xml
